/**
 * Revoke one API key.
 *
 * Revocation is preferred over deletion on purpose: the row stays as an audit
 * record, `revokedAt` is stamped, and the key stops authenticating immediately.
 * `ApiKeyService.revoke` scopes the update by `userId`, so one user can never
 * revoke another user's key — an id they do not own simply reports 404.
 */
import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/auth/guard";
import { toErrorResponse } from "@/lib/api/errors";
import { ApiKeyService } from "@/lib/gateway/api-key-store";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/** Ids are generated by NEXA; anything else is malformed, not merely unknown. */
const ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/;

export async function DELETE(
  req: NextRequest,
  props: { params: Promise<{ id: string }> }
) {
  try {
    const user = await requireUser(req);
    const { id } = await props.params;

    if (!ID_PATTERN.test(id ?? "")) {
      return NextResponse.json({ error: "That key id is not valid." }, { status: 400 });
    }

    const revoked = await ApiKeyService.revoke(user.id, id);
    if (!revoked) {
      // 404 for both "does not exist" and "belongs to someone else", so the
      // response cannot be used to probe for other users' key ids.
      return NextResponse.json({ error: "Key not found." }, { status: 404 });
    }

    return NextResponse.json({ ok: true, revokedId: id });
  } catch (err) {
    return toErrorResponse(err, { request: req });
  }
}
